In [1]:
# Importing the required packages
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv("training_data.csv")
df

,Unnamed: 0,Unnamed: 0.1,Gender,new_age,new_o2sat,new_temp,new_bp,new_resp,new_map,new_fio2,new_hr,HospAdmTime,ICULOS,SepsisLabel
0,0,0,0,1,1,0,0,1,0,0,0,-0.03,1,0
1,1,1,0,1,2,0,0,2,2,0,0,-0.03,2,0
2,2,2,0,1,2,0,0,0,2,0,0,-0.03,3,0
3,3,3,0,1,2,0,0,0,0,0,0,-0.03,4,0
4,4,4,0,1,0,0,0,0,2,2,1,-0.03,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789741,789741,789749,0,1,1,0,0,2,2,0,0,-10.58,38,0
789742,789742,789750,0,1,1,2,0,2,2,2,1,-10.58,39,0
789743,789743,789751,0,1,1,0,0,0,2,0,1,-10.58,40,0
789744,789744,789752,0,1,2,0,0,0,0,0,1,-10.58,41,0
789745,789745,789753,0,1,1,0,0,1,0,0,0,-10.58,42,0

In [3]:
# Function importing Dataset
def importdata():
    balance_data = pd.read_csv("training_data.csv")
      
    # Printing the dataswet shape
    print ("Dataset Length: ", len(balance_data))
    print ("Dataset Shape: ", balance_data.shape)
      
    # Printing the dataset obseravtions
    #print ("Dataset: ",balance_data.head())
    return balance_data

In [4]:
# Function to split the dataset
def splitdataset(balance_data):
  
    # Separating the target variable
    cols = ['Gender', 'new_age', 'new_o2sat', 'new_temp', 'new_bp', 'new_resp', 'new_map', 'new_fio2', 'new_hr', 'HospAdmTime', 'ICULOS']

    X = balance_data[cols]
    Y = balance_data['SepsisLabel']
  
    # Splitting the dataset into train and test
    X_train, X_test, y_train, y_test = train_test_split( 
    X, Y, test_size = 0.3, random_state = 100)
      
    return X, Y, X_train, X_test, y_train, y_test

In [5]:
# Function to perform training with giniIndex.
def train_using_gini(X_train, X_test, y_train):
  
    # Creating the classifier object
    clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 100,max_depth=10, min_samples_leaf=3,min_samples_split=20)
  
    # Performing training
    clf_gini.fit(X_train, y_train)
    return clf_gini

In [6]:
# Function to perform training with entropy.
def tarin_using_entropy(X_train, X_test, y_train):
  
    # Decision tree with entropy
    clf_entropy = DecisionTreeClassifier(
            criterion = "entropy", random_state = 100,
            max_depth = 10, min_samples_leaf = 3,min_samples_split=20)
  
    # Performing training
    clf_entropy.fit(X_train, y_train)
    return clf_entropy

In [7]:
# Function to make predictions
def prediction(X_test, clf_object):
  
    # Predicton on test with giniIndex
    y_pred = clf_object.predict(X_test)
    print("Predicted values:")
    #print(*y_pred)
    return y_pred

In [8]:
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
      
    print("Confusion Matrix: ",
        confusion_matrix(y_test, y_pred))
      
    print ("Accuracy : ",
    accuracy_score(y_test,y_pred)*100)
      
    print("Report : ",
    classification_report(y_test, y_pred))

In [9]:
def main():
      
    # Building Phase
    data = importdata()
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data)
    clf_gini = train_using_gini(X_train, X_test, y_train)
    clf_entropy = tarin_using_entropy(X_train, X_test, y_train)
      
    # Operational Phase
    print("Results Using Gini Index:")
      
    # Prediction using gini
    y_pred_gini = prediction(X_test, clf_gini)
    cal_accuracy(y_test, y_pred_gini)
      
    print("Results Using Entropy:")
    # Prediction using entropy
    y_pred_entropy = prediction(X_test, clf_entropy)
    cal_accuracy(y_test, y_pred_entropy)

In [10]:
if __name__=="__main__":
    main()

Dataset Length:  789746
Dataset Shape:  (789746, 14)
Results Using Gini Index:
Predicted values:
Confusion Matrix:  [[231588    159]
 [  4969    208]]
Accuracy :  97.83559284833954
Report :                precision    recall  f1-score   support

           0       0.98      1.00      0.99    231747
           1       0.57      0.04      0.08      5177

    accuracy                           0.98    236924
   macro avg       0.77      0.52      0.53    236924
weighted avg       0.97      0.98      0.97    236924

Results Using Entropy:
Predicted values:
Confusion Matrix:  [[231650     97]
 [  5039    138]]
Accuracy :  97.83221623811855
Report :                precision    recall  f1-score   support

           0       0.98      1.00      0.99    231747
           1       0.59      0.03      0.05      5177

    accuracy                           0.98    236924
   macro avg       0.78      0.51      0.52    236924
weighted avg       0.97      0.98      0.97    236924